import { PERMISSION } from "@/constant/permission";
import { ROLE } from "@/constant/role";

export const AdminRoles = [ROLE.ADMIN];
export const AdminPermissions = [
    PERMISSION.READ_LIST_ROLE,
    PERMISSION.READ_DETAIL_ROLE,
    PERMISSION.CREATE_ROLE,
    PERMISSION.UPDATE_ROLE,
    PERMISSION.DELETE_ROLE,

    PERMISSION.READ_LIST_USER,
    PERMISSION.READ_DETAIL_USER,
    PERMISSION.CREATE_USER,
    PERMISSION.UPDATE_USER,
    PERMISSION.DELETE_USER,

    PERMISSION.READ_LIST_PERMISSION,
    PERMISSION.READ_DETAIL_PERMISSION,
    PERMISSION.CREATE_PERMISSION,
    PERMISSION.UPDATE_PERMISSION,
    PERMISSION.DELETE_PERMISSION,

    PERMISSION.READ_LIST_LOCATION,
    PERMISSION.READ_DETAIL_LOCATION,
    PERMISSION.CREATE_LOCATION,
    PERMISSION.UPDATE_LOCATION,
    PERMISSION.DELETE_LOCATION,

    PERMISSION.READ_LIST_TRANSPORT,
    PERMISSION.READ_DETAIL_TRANSPORT,
    PERMISSION.CREATE_TRANSPORT,
    PERMISSION.UPDATE_TRANSPORT,
    PERMISSION.DELETE_TRANSPORT,

    PERMISSION.READ_LIST_ROUTE,
    PERMISSION.READ_DETAIL_ROUTE,
    PERMISSION.CREATE_ROUTE,
    PERMISSION.UPDATE_ROUTE,
    PERMISSION.DELETE_ROUTE,

    PERMISSION.ASSIGN_PERMISSION_TO_ROLE,
    PERMISSION.ASSIGN_ROLE_TO_USER,
];