export enum PERMISSION {
    // SERVICEAUTH:

    //ROLE
    READ_LIST_ROLE = 'READ_LIST_ROLE',
    READ_DETAIL_ROLE = 'READ_DETAIL_ROLE',
    CREATE_ROLE = 'CREATE_ROLE',
    UPDATE_ROLE = 'UPDATE_ROLE',
    DELETE_ROLE = 'DELETE_ROLE',

    //USER
    READ_LIST_USER = 'READ_LIST_USER',
    READ_DETAIL_USER = 'READ_DETAIL_USER',
    CREATE_USER = 'CREATE_USER',
    UPDATE_USER = 'UPDATE_USER',
    DELETE_USER = 'DELETE_USER',

    //PERMISSION
    READ_LIST_PERMISSION = 'READ_LIST_PERMISSION',
    READ_DETAIL_PERMISSION = 'READ_DETAIL_PERMISSION',
    CREATE_PERMISSION = 'CREATE_PERMISSION',
    UPDATE_PERMISSION = 'UPDATE_PERMISSION',
    DELETE_PERMISSION = 'DELETE_PERMISSION',

    // SERVICEROUTE:

    //LOCATION
    READ_LIST_LOCATION = 'READ_LIST_LOCATION',
    READ_DETAIL_LOCATION = 'READ_DETAIL_LOCATION',
    CREATE_LOCATION = 'CREATE_LOCATION',
    UPDATE_LOCATION = 'UPDATE_LOCATION',
    DELETE_LOCATION = 'DELETE_LOCATION',

    //TRANSPORT
    READ_LIST_TRANSPORT = 'READ_LIST_TRANSPORT',
    READ_DETAIL_TRANSPORT = 'READ_DETAIL_TRANSPORT',
    CREATE_TRANSPORT = 'CREATE_TRANSPORT',
    UPDATE_TRANSPORT = 'UPDATE_TRANSPORT',
    DELETE_TRANSPORT = 'DELETE_TRANSPORT',

    //ROUTE
    READ_LIST_ROUTE = 'READ_LIST_ROUTE',
    READ_DETAIL_ROUTE = 'READ_DETAIL_ROUTE',
    CREATE_ROUTE = 'CREATE_ROUTE',
    UPDATE_ROUTE = 'UPDATE_ROUTE',
    DELETE_ROUTE = 'DELETE_ROUTE',

    //OTHER
    ASSIGN_PERMISSION_TO_ROLE = 'ASSIGN_PERMISSION_TO_ROLE',
    ASSIGN_ROLE_TO_USER = 'ASSIGN_ROLE_TO_USER',

}