import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import StyledComponentsRegistry from "@/lib/antd/AntdRegistry";
import { ConfigProvider } from "antd";
import { COLOR } from "@/constant";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: COLOR.PRIMARY,
                borderRadius: 2,
                colorText: "#000",
                colorBgContainer: COLOR.BACKGROUND,
              },
              components: {
                Layout: {
                  headerBg: "#fff",
                  headerHeight: 80,
                  footerBg: "#fff",
                  colorBgLayout: "#fff",
                },
                Menu: {
                  colorBgContainer: "#fff",
                },
                Breadcrumb: {
                  colorText: COLOR.PRIMARY,
                },
              },
            }}
          >
            <Providers>{children}</Providers>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
