export enum STATUS {
    SUCCESS = 'SUCCESS',
    CREATE = 'CREATE',
    FAILURE = 'FAILURE',
    PENDING = 'PENDING',

    ERR_AUTH_LOGIN = 'ERR_AUTH_LOGIN',
    ERR_FORBIDDEN = 'ERR_FORBIDDEN',
    ERR_NOT_FOUND = 'ERR_NOT_FOUND',
    ERR_VALIDATION = 'ERR_VALIDATION',
    ERR_INTERNAL_SERVER = 'ERR_INTERNAL_SERVER',
    ERR_NETWORK_ERROR = 'ERR_NETWORK_ERROR',
    ERR_TOKEN_EXPIRED = 'ERR_TOKEN_EXPIRED',
    ERR_TOKEN_INVALID = 'ERR_TOKEN_INVALID',
    ERR_UNKNOWN_AUTH_ERROR = 'ERR_UNKNOWN_AUTH_ERROR',
    ERR_ROLE_USER = 'ERR_ROLE_USER',
    ERR_PERMISSION_USER = 'ERR_PERMISSION_USER',
    ERR_REFRESH_TOKEN = 'ERR_REFRESH_TOKEN_EXPIRED_OR_INVALID',
    VALIDATION_ERROR = "VALIDATION_ERROR"
}

export enum STATUS_CODE {
    SUCCESS = 200,
    CREATE = 201,
    FAILURE = 400,
    FORBIDDEN = 403,
    ERR_AUTH_LOGIN = 401,
    ERR_NOT_FOUND = 404,
    ERR_VALIDATION = 422,
    ERR_INTERNAL_SERVER = 500,
    ERR_NETWORK_ERROR = 503,
    ERR_TOKEN_EXPIRED = 401,
    ERR_TOKEN_INVALID = 401,
    ERR_UNKNOWN_AUTH_ERROR = 401,
    ERR_ROLE_USER = 403,
    ERR_PERMISSION_USER = 403,
    ERR_REFRESH_TOKEN = 401,
}
