// 'use client';

import type { Metadata } from "next";
import { Cookie, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import StyledComponentsRegistry from "@/lib/antd/AntdRegistry";
import { ConfigProvider } from "antd";
import { COLOR } from "@/constant";
import LogoImage from "@/public/logo/logoImage.png";
import CookiesComponent from "@/components/auth/cookies";
import "mapbox-gl/dist/mapbox-gl.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "S-Routing",
  description: "Generated by create E-Routing",
  icons: {
    icon: LogoImage.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: COLOR.PRIMARY,
                borderRadius: 2,
                colorText: "#000",
                colorBgContainer: COLOR.BACKGROUND,
                fontSize: 16,
              },
              components: {
                Layout: {
                  headerBg: "#fff",
                  headerHeight: 80,
                  footerBg: "#fff",
                  colorBgLayout: "#fff",
                },
                Menu: {
                  colorBgContainer: "#fff",
                },
                Breadcrumb: {
                  colorText: COLOR.PRIMARY,
                },
                Button: {
                  borderRadius: 8,
                },
                Modal: {
                  borderRadius: 8,
                },
                Table: {
                  colorBgContainer: "#fff",
                  borderRadius: 8,
                },
                Input:{
                  colorTextDisabled: "#868e96"
                }
              },
            }}
          >
            <Providers>
              <CookiesComponent />
              {children}
            </Providers>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
