import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import StyledComponentsRegistry from "@/lib/antd/AntdRegistry";
import { ConfigProvider } from "antd";
import { COLOR } from "@/constant";
import LogoImage from "@/public/logo/logoImage.png";
import CookiesComponent from "@/components/auth/cookies";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "S-Routing",
  description: "Generated by create E-Routing",
  icons: {
    icon: LogoImage.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{background: "#f8f9fa"}}>
        <StyledComponentsRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: COLOR.PRIMARY,
                borderRadius: 2,
                colorText: "#000",
                colorBgContainer: COLOR.BACKGROUND,
                fontSize: 16,
              },
              components: {
                Layout: {
                  headerBg: COLOR.BACKGROUND,
                  footerBg: COLOR.BACKGROUND,
                  colorBgLayout: COLOR.BACKGROUNDLAYOUT,
                  headerHeight: 70,
                },
                Menu: {
                  colorBgContainer: COLOR.BACKGROUND,
                },
                Breadcrumb: {
                  colorText: COLOR.PRIMARY,
                },
                Button: {
                  borderRadius: 8,
                },
              },
            }}
          >
            <Providers>
              <CookiesComponent />
              {children}
            </Providers>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
